[snowflake]
account = AQB45833
user = SUPREMEPOTATO1
password = 4Now5Me6Later9?
warehouse = "RARE_WH"
database = "RAREINDEX_DB"
schema = "PUBLIC"
role = "RARE_APP_ROLE"

[newsapi]
key = "caf9439a21fd45c88227642c71cc008e"

[brickset]
key = "3-CugE-sT9S-5ZLHh"

[pokeprice]
key = "pokeprice_pro_285ef2b6bba3a740ec0b0ded5ef546a7ff0d3add241f6d93"

[watchapi]
key = "SmUxMzSep6ywfrLexFPxSqRJ9amcb8rvuJV1R7nA"

[justcg]
key = "tcg_5810a72c66e9471b8cc2c0e91466e3e7"

